[package]
name = "ziggy-example"
version = "0.1.0"
edition = "2021"

[dependencies]
url = { git = "https://github.com/servo/rust-url", rev = "bfa167b4e0253642b6766a7aa74a99df60a94048" }
ziggy = { path = "../" }