[package]
name = "ziggy"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
description = "A multi-fuzzer management utility for all of your Rust fuzzing needs 🧑‍🎤"
repository = "https://github.com/srlabs/ziggy/"

[dependencies]
clap = { version = "3.2.22", features = ["cargo", "derive"], optional = true }
console = { version = "0.15.1", optional = true }
glob = { version = "0.3.0", optional = true }
libfuzzer-sys = { version = "0.4.4", optional = true }
afl = { version = "0.12.8", default-features = false, optional = true }
honggfuzz = { version = "0.5.55", optional = true }

[features]
default = ["cli"]
cli = ["clap", "console", "glob"]
reset_lazy_static = ["afl?/reset_lazy_static"]
