[package]
name = "ziggy"
version = "0.2.3"
edition = "2021"
license = "Apache-2.0"
description = "A multi-fuzzer management utility for all of your Rust fuzzing needs 🧑‍🎤"
repository = "https://github.com/srlabs/ziggy/"

[dependencies]
clap = { version = "4.0.18", features = ["cargo", "derive"], optional = true }
console = { version = "0.15.2", optional = true }
glob = { version = "0.3.0", optional = true }
toml = { version = "0.5.9", optional = true }
anyhow = { version = "1.0.66", optional = true }
libfuzzer-sys = { version = "0.4.5", optional = true }
afl = { version = "0.12.9", default-features = false, optional = true }
honggfuzz = { version = "0.5.55", optional = true }

[features]
default = ["cli"]
cli = ["clap", "console", "glob", "toml", "anyhow"]
reset_lazy_static = ["afl?/reset_lazy_static"]
