[package]
name = "ziggy"
version = "0.1.9"
edition = "2021"
license = "Apache-2.0"
description = "A multi-fuzzer management utility for all of your Rust fuzzing needs 🧑‍🎤"
repository = "https://github.com/srlabs/ziggy/"

[dependencies]
clap = { version = "3.2.15", features = ["cargo", "derive"], optional = true }
console = { version = "0.15.0", optional = true }
glob = { version = "0.3.0", optional = true }
libfuzzer-sys = { version = "0.4.3", optional = true }
afl = { version = "0.12.4", optional = true }
honggfuzz = { version = "0.5.54", optional = true }
arbitrary = { version = "1", features = ["derive"], optional = true }

[features]
default = ["cli"]
cli = ["clap", "console", "glob"]
honggfuzz = ["dep:honggfuzz", "arbitrary"]
afl = ["dep:afl", "arbitrary"]
libfuzzer-sys = ["dep:libfuzzer-sys", "arbitrary"]
