[package]
name = "ziggy"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "A multi-fuzzer management utility for all of your Rust fuzzing needs 🧑‍🎤"
repository = "https://github.com/srlabs/ziggy/"

[dependencies]
clap = { version = "3.1.18", features = ["cargo"] }
