[package]
name = "ziggy"
version = "1.0.0"
edition = "2021"
license = "Apache-2.0"
description = "A multi-fuzzer management utility for all of your Rust fuzzing needs 🧑‍🎤"
repository = "https://github.com/srlabs/ziggy/"

[workspace]
members = [
    ".",
    "examples/arbitrary",
    "examples/url",
]

[dependencies]
afl = { version = "0.15.5", default-features = false, optional = true }
anyhow = { version = "1.0.83", optional = true }
cargo_metadata = { version = "0.18.1", optional = true }
clap = { version = "4.5.4", features = ["cargo", "derive", "env"], optional = true }
console = { version = "0.15.8", optional = true }
env_logger = { version = "0.11.3", optional = true }
fork = { version = "0.1.23", optional = true }
glob = { version = "0.3.1", optional = true }
# We use our own fork of honggfuzz to use the tool's latest release
# https://github.com/rust-fuzz/honggfuzz-rs/pull/85
honggfuzz = { package = "ziggy-honggfuzz-2", version = "0.5.55", optional = true }
libc = { version = "0.2.154", optional = true }
log = { version = "0.4.21", optional = true }
semver = { version = "1.0.23", optional = true }
serde_json = { version = "1.0.116", optional = true }
strip-ansi-escapes = { version = "0.2.0", optional = true }
time-humanize = { version = "0.1.3", optional = true }
toml = { version = "0.8.12", optional = true }

[features]
default = ["cli"]
cli = [
    "clap",
    "console",
    "glob",
    "toml",
    "semver",
    "anyhow",
    "serde_json",
    "log",
    "env_logger",
    "strip-ansi-escapes",
    "libc",
    "time-humanize",
    "cargo_metadata",
]
coverage = ["fork", "libc"]
