[package]
name = "ziggy"
version = "0.4.1"
edition = "2021"
license = "Apache-2.0"
description = "A multi-fuzzer management utility for all of your Rust fuzzing needs 🧑‍🎤"
repository = "https://github.com/srlabs/ziggy/"

[dependencies]
clap = { version = "4.1.4", features = ["cargo", "derive"], optional = true }
console = { version = "0.15.5", optional = true }
glob = { version = "0.3.1", optional = true }
toml = { version = "0.7.2", optional = true }
anyhow = { version = "1.0.69", optional = true }
afl = { version = "0.12.12", default-features = false, optional = true }
honggfuzz = { version = "0.5.55", optional = true }
signal-hook = "0.3.15"

[features]
default = ["cli"]
cli = ["clap", "console", "glob", "toml", "anyhow"]
reset_lazy_static = ["afl?/reset_lazy_static"]
